# Generated by Django 4.2.2 on 2023-10-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_remove_plato_orden_orden_plato'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Mesa',
        ),
        migrations.DeleteModel(
            name='Membresia',
        ),
    ]
